import { Sparkles, BarChart2, Mail, FileText, Plus, LayoutDashboard, User } from "lucide-react";
export const FEATURES=[
{

    icon:Sparkles,
    title:"AI Invoice Creation",
    description:"Paste any text,email,or recipt, and let our AI instantly generate a complete invoice for you."
},
{
    icon:BarChart2,
    title:"AI Powered Dashboard",
    description:"Get smart insights into your invoicing patterns, payment trends, and financial health with our AI-powered dashboard."
},
{
    icon:Mail,
    title:"Smart Reminders",
    description:"Automate payment reminders with personalized messages generated by AI, ensuring timely payments from your clients."
},
{
    icon:FileText,
    title:"Easy Invoice Management",
    description:"Organize, track, and manage all your invoices in one place with our user-friendly interface."
},
];

export const TESTIMONIALS=[{
    quote:"This invoicing app has transformed the way I manage my business finances. The AI-powered features save me so much time and effort!",
    author:"John Doe",
    title:"Effortless Invoicing with AI",
    avatar:"https://randomuser.me/api/portraits",
},
{
    quote:"I love how easy it is to create and manage invoices with this app. The AI features are a game-changer for my small business.",
    author:"Jane Smith",
    title:"Streamlined Invoicing for Freelancers",
    avatar:"https://randomuser.me/api/portraits",
},
{
    quote:"The AI-powered dashboard provides valuable insights into my invoicing patterns and helps me make informed financial decisions.",
    author:"Michael Johnson",
    title:"Data-Driven Invoicing Insights",
    avatar:"https://randomuser.me/api/portraits",
},
{
    quote:"The smart reminders have significantly improved my payment collection process. I no longer have to worry about late payments.",
    author:"Emily Davis",
    title:"Automated Payment Reminders",
    avatar:"https://randomuser.me/api/portraits",   
}
];

export const FAQ=[
    {
        question:"How does the AI invoice creation work?",
        answer:"Our AI invoice creation feature uses natural language processing to analyze the text you provide, whether it's an email, receipt, or any other document. It then extracts relevant information such as client details, items, prices, and due dates to generate a complete invoice for you."    
    },
    {
        question:"Is my data secure with this invoicing app?",
        answer:"Yes, we take data security very seriously. We use industry-standard encryption and security measures to protect your data. Your information is stored securely and is only accessible to you."
    },
    {
        question:"Can I customize the invoice templates?",
        answer:"Currently, we offer a selection of professionally designed invoice templates that you can choose from. We are working on adding more customization options in the future to allow you to personalize your invoices further."
    },
    {
        question:"How do the smart reminders work?",
        answer:"Our smart reminders feature allows you to set up automated payment reminders for your clients. You can customize the message and schedule for the reminders, and our AI will ensure that they are sent out at the right time to help you get paid on time."
    },
];

//Navigation item configurations for dashboard layout
export const NAVIGATION_MENU=[
    {id:"dashboard",name:"Dashboard",icon:LayoutDashboard},
    {id:"invoices",name:"Invoices",icon:FileText},
    {id:"profile",name:"Profile",icon:User},
    {id:"invoices/new",name:"Create Invoice",icon:Plus}

]